from stocks.adobestock import Adobestock
from stocks.bigstockphoto import Bigstockphoto
from stocks.deposit import Deposit
from stocks.flickr import Flickr
from stocks.istockphoto import Istockphoto
from stocks.pexels import Pexels
from stocks.pinterest import Pinterest
from stocks.pixabay import Pixabay
from stocks.shutterstock import Shutterstock
from stocks.stockphoto import Stockphoto
from stocks.stocksnap import Stocksnap
from stocks.stockvault import Stockvault
from stocks.unsplash import Unsplash